/**
 * Comprehensive Master Data Seed & Initial State for SAS-AEIT
 * Direct Incomes, Direct Expenses, Assets, Vehicles & Audit Trails
 */

export interface MasterCategorySeed {
  name: string;
  type: 'INCOME' | 'EXPENSE';
  subcategories: string[];
}

export const MASTER_CATEGORIES_DATA: MasterCategorySeed[] = [
  // --- DIRECT INCOME CATEGORIES ---
  {
    name: 'Payer',
    type: 'INCOME',
    subcategories: ['My Govt', 'Institution', 'Project', 'Buyer', 'Bank'],
  },
  {
    name: 'Govt Payments',
    type: 'INCOME',
    subcategories: [
      'Salary',
      'Arrears',
      'Monthly Travel Bill',
      'Travel Bill',
      'Cash Incentive',
      'Awards',
      'Rewards',
      'Honorarium',
      'Special Duty Pay',
      'Bangla Noboborsho',
      'Festival Allowance',
      'Training Bill',
      'Others',
    ],
  },
  {
    name: 'Loan',
    type: 'INCOME',
    subcategories: ['Bank', 'Credit Card', 'Personal Borrow'],
  },

  // --- DIRECT EXPENSE CATEGORIES ---
  {
    name: 'Payee',
    type: 'EXPENSE',
    subcategories: [
      'Super shop',
      'Shopkeeper',
      'Grocers',
      'Counter',
      'Supplier',
      'Project Bank',
    ],
  },
  {
    name: 'Accommodations',
    type: 'EXPENSE',
    subcategories: ['Govt Quarter', 'Govt Dorms', 'Private Flat', 'Others'],
  },
  {
    name: 'Utilities',
    type: 'EXPENSE',
    subcategories: [
      'Electricity',
      'Gas',
      'Water & Sewer services',
      'Trash and recycling collection',
      'Others',
    ],
  },
  {
    name: 'Connectivity',
    type: 'EXPENSE',
    subcategories: [
      'High-speed internet',
      'Landline',
      'Mobile phone plans',
      'Cable or digital TV services',
      'Others',
    ],
  },
  {
    name: 'Fish',
    type: 'EXPENSE',
    subcategories: [
      'Ilish (Hilsa)',
      'Rui (Rohu)',
      'Katla (Catla)',
      'Mrigal',
      'Kalibaush',
      'Mola',
      'Kachki',
      'Puti',
      'Chapila',
      'Batasi',
      'Dhela',
      'Pabda',
      'Magur',
      'Shingh',
      'Aar (Ayre)',
      'Bagayre',
      'Boal',
      'Pangas',
      'Rita',
      'Gatka',
      'Koi',
      'Taki',
      'Shol',
      'Gajar',
      'Baim',
      'Chital',
      'Rupchanda',
      'Loitta',
      'Bhetki (Koral)',
      'Meni-Poa',
      'Topshi',
      'Churi',
      'Others',
    ],
  },
  {
    name: 'Meat',
    type: 'EXPENSE',
    subcategories: [
      'Beef',
      'Goat',
      'Beefalo',
      'Duck',
      'Chicken-Deshi',
      'Chicken-Poultry',
      'Chicken-Sonali',
      'Chicken-Layer',
    ],
  },
  {
    name: 'Egg',
    type: 'EXPENSE',
    subcategories: ['Chicken', 'Ducks', 'Farm'],
  },
  {
    name: 'Spices',
    type: 'EXPENSE',
    subcategories: [
      'Holud (Turmeric)',
      'Morich (Dry Red Chili)',
      'Dhonia (Coriander)',
      'Jeera (Cumin)',
      'Kalo Jeera (Black Cumin)',
      'Radhuni',
      'Ada (Ginger)',
      'Roshun (Garlic)',
      'Piyaj (Onion)',
      'Kacha Morich (Green Chili)',
      'Tejpatta (Bay Leaf)',
      'Elachi (Green Cardamom)',
      'Boro Elachi (Black Cardamom)',
      'Daruchini (Cinnamon)',
      'Lobongo (Cloves)',
      'Gol Morich (Black Pepper)',
      'Joyitri (Mace)',
      'Joyphol (Nutmeg)',
      'Mouri (Fennel Seeds)',
      'Methi (Fenugreek Seeds)',
      'Shorshe (Mustard Seeds)',
      'Posto Dana (Poppy Seeds)',
      'Tishi (Flaxseeds)',
      'Panch Phoron',
      'Garam Masala',
      'Chotpoti Masala',
    ],
  },
  {
    name: 'Oil',
    type: 'EXPENSE',
    subcategories: ['Shorshe', 'Soyabean', 'Coconut', 'Surjomukhi (Sunflower)', 'Mixed'],
  },
  {
    name: 'Food Grains',
    type: 'EXPENSE',
    subcategories: ['Flavored Rice', 'Rice', 'Wheat', 'Barley'],
  },
  {
    name: 'Vegetable',
    type: 'EXPENSE',
    subcategories: [
      'Aloo (Potato)',
      'Phoolkopi (Cauliflower)',
      'Badhakopi (Cabbage)',
      'Shim (Flat Green Beans)',
      'Gajor (Carrot)',
      'Tomato',
      'Mula (Radish)',
      'Ool Kopi (Kohlrabi)',
      'Salgam (Turnip)',
      'Begun (Eggplant)',
      'Motorchuti (Green Peas)',
      'Jhinge (Ridge Gourd)',
      'Dhundul (Sponge Gourd)',
      'Chichinga (Snake Gourd)',
      'Korola/Uchhe (Bitter Gourd)',
      'Patal (Pointed Gourd)',
      'Chal Kumra (Ash Gourd)',
      'Misti Kumra (Pumpkin)',
      'Lau/Kaddu (Bottle Gourd)',
      'Kakrol (Teasel Gourd)',
      'Dherosh (Okra)',
      'Barbati (Yardlong Beans)',
      'Mukhikochu (Taro Root)',
      'Ool Kochu (Elephant Foot Yam)',
      'Misti Aloo (Sweet Potato)',
      'Shakh Aloo (Yam Bean)',
      'Kacha Pepe (Green Papaya)',
      'Kacha Kola (Green Banana)',
      'Mocha (Banana Flower)',
      'Thor (Banana Stem)',
      'Data (Amaranth Stems)',
      'Kochur Lati (Taro Stolons)',
      'Baansh Korol (Bamboo Shoots)',
    ],
  },
  {
    name: 'Vegetable-Soft',
    type: 'EXPENSE',
    subcategories: [
      'Lal Shak (Red Amaranth)',
      'Palong Shak (Spinach)',
      'Pui Shak (Malabar Spinach)',
      'Data Shak (Stem Amaranth)',
      'Kolmi Shak (Water Spinach)',
      'Sorshe Shak (Mustard Greens)',
      'Mula Shak (Radish Greens)',
      'Pata Kopi (Cabbage Leaves)',
      'Mayna Shak',
      'Helencha Shak',
      'Kheta Shak',
      'Thankuni Shak',
      'Telakucha Shak',
    ],
  },
  {
    name: 'Fruits',
    type: 'EXPENSE',
    subcategories: [
      'Aam (Mango)',
      'Kathal (Jackfruit)',
      'Lichu (Lychee)',
      'Kalojaam (Blackberry)',
      'Lotkon (Burmese Grape)',
      'Taal (Ice Apple)',
      'Jamrul (Water Apple)',
      'Anarosh (Pineapple)',
      'Tormuj (Watermelon)',
      'Bangi (Muskmelon)',
      'Gub (Velvet Apple)',
      'Kola (Banana)',
      'Pepe (Papaya)',
      'Peyara (Guava)',
      'Kamranga (Star Fruit)',
      'Lebu (Lime/Lemon)',
      'Kagoji Lebu (Key Lime)',
      'Dub/Narikel (Green/Mature Coconut)',
      'Amra (Hog Plum)',
      'Karamcha',
      'Ata (Custard Apple)',
      'Chalta (Elephant Apple)',
      'Boroi/Kul (Jujube)',
      'Komola (Mandarin Orange)',
      'Batabi Lebu (Pomelo)',
      'Bedana/Dalim (Pomegranate)',
      'Safeda (Sapodilla)',
      'Boichi',
      'Dehua',
      'Bel (Wood Apple)',
      'Kadbel',
      'Tentul (Tamarind)',
      'Amloki (Amla)',
      'Haritaki',
      'Tipa Fruit',
      'Others',
    ],
  },
  {
    name: 'Household',
    type: 'EXPENSE',
    subcategories: [
      'Toilet paper',
      'Soap',
      'Cleaning supplies',
      'Trash bags',
      'Drinking water delivery/filtration',
      'Pantry Items',
      'Toilet Items',
      'Others',
    ],
  },
  {
    name: 'Food',
    type: 'EXPENSE',
    subcategories: [
      'Dining out',
      'Work/school lunches',
      'Takeout and food delivery services',
      'Others',
    ],
  },
  {
    name: 'Transportation & Commuting',
    type: 'EXPENSE',
    subcategories: [
      'Vehicle loan/lease payments',
      'Auto insurance',
      'Fuel',
      'Public transit passes',
      'Tolls & parking fees',
      'Rideshares (Uber/Taxi)',
      'Vehicle maintenance & registration',
    ],
  },
  {
    name: 'Children, Education & Family Care',
    type: 'EXPENSE',
    subcategories: [
      'Childcare/daycare',
      'Tuition fees & uniforms',
      'School supplies & books',
      'Extracurricular activities',
      'Pocket money',
      'Edu_Materials',
      'Transport rent',
      'Others',
    ],
  },
  {
    name: 'Healthcare & Wellness',
    type: 'EXPENSE',
    subcategories: [
      'Health insurance',
      'Doctor fees',
      'Prescription/OTC drugs',
      'Dental care',
      'Vision care',
      'Mental health therapy',
      'Gym memberships',
      'Hospital bills',
      'Test fees',
      'Others',
    ],
  },
  {
    name: 'Personal Care & Clothing',
    type: 'EXPENSE',
    subcategories: [
      'Apparel & shoes',
      'Dry cleaning & laundry',
      'Haircuts & salon visits',
      'Grooming supplies',
      'Cosmetics & skincare',
      'Hygiene products',
      'Others',
    ],
  },
  {
    name: 'Entertainment, Leisure & Subscriptions',
    type: 'EXPENSE',
    subcategories: [
      'Streaming services',
      'Hobbies & craft supplies',
      'Movie tickets',
      'Concerts & event admissions',
      'Hosting & parties',
      'Social gatherings',
      'Others',
    ],
  },
  {
    name: 'Travel/Tour',
    type: 'EXPENSE',
    subcategories: [
      'Passport & Visa fees',
      'Travel insurance',
      'Immunizations & medical kits',
      'Gear & apparel',
      'Flights',
      'Train & Bus',
      'Local transportation',
      'Cruises & ferries',
      'Personal vehicle commute',
      'Hotel/Resort rent',
      'Tips',
      'Gifts & souvenirs',
      'Dining',
      'Shopping',
      'Others',
    ],
  },
  {
    name: 'Vacation & Family Trip',
    type: 'EXPENSE',
    subcategories: [
      'Passport & Visas',
      'Travel insurance',
      'Trip shopping',
      'Travel health',
      'Family transportation',
      'Road trip costs (Fuel, Tolls, Pre-trip maintenance)',
      'Parking',
      'Hotel/Resort rent',
      'Dining',
      'Snacks',
      'Sightseeing & Theme parks',
      'Family keepsakes',
      'Gifts',
    ],
  },
  {
    name: 'Financial Obligations & Debt',
    type: 'EXPENSE',
    subcategories: ['Credit card balances', 'Loan payments', 'Bank/transfer fees'],
  },
  {
    name: 'Gifts & Miscellaneous',
    type: 'EXPENSE',
    subcategories: [
      'Birthday gifts',
      'Anniversary gifts',
      'Holiday gifts',
      'Pet food & care',
      'Charitable donations/tithes',
      'Legal & professional service fees',
    ],
  },
];
